### ISSUE TITLE
error during build: TypeError: callback.apply is not a function

### ISSUE THREAD

**Issue by cizkey** [antfu/utils#21]
### Describe the bug

When using the latest version (v6.0.1), build reports an error with the following error message. It is available to use the previous v0.5.2.

![image](https://user-images.githubusercontent.com/14026236/199148978-0595f670-b732-483f-9659-5405f39f7f3f.png)

### Reproduction

sorry, Unable to provide

### System Info

```Shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
    Memory: 5.51 GB / 14.88 GB
  Binaries:
    Node: 14.19.0 - D:\Programs\nodejs\node.EXE
    Yarn: 1.22.17 - D:\Programs\nodejs\yarn.CMD
    npm: 6.14.16 - D:\Programs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yeli19950109** [comment]
0.6.0 not have this error but 0.6.1 has this error

**Comment by xlanghejianfeng** [comment]
这个是哪个的依赖呢，现在打包报错，需要锁包

**Comment by yuuki2017** [comment]
same err

**Comment by xlanghejianfeng** [comment]
unplugin-vue-components 锁定版本后好了

**Comment by bynowi** [comment]
unplugin-vue-components 锁定版本 0.22.8

**Comment by geedys** [comment]
使用unplugin-auto-import@0.11.3以上也有这个问题
