### ISSUE TITLE
Improve Prototype Pollution fix coverage 

### ISSUE THREAD

**Issue by vphilot** [antfu/utils#36]
### Clear and concise description of the problem

Re: https://huntr.dev/bounties/009f1cd9-401c-49a7-bd08-be35cff6faef/

Thank you for all your hard work on fixing vulnerabilities on the utils lib. 

Even after fix on 7.3, platforms such as SonaType are still flagging this package as insecure because one file wasn't updated (index.js) even though the commonJS and ESM versions are clear. 

Quote:

> The fix for this vulnerability was released for version 0.7.3 and onwards only on the index.mjs and index.cjs files. However the index.js file remains vulnerable.

### Suggested solution

index.js should also include the Prototype Pollution fix 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for reporting. The `index.js` was probably from a stale build that was mistakenly not removed in the later builds. Use published a new version without it. As it was actually possible to be referenced, I consider it not a serve issue. Closing. Thanks.
